Content:
    swift:
        root_dir: ${ROOT_DIR}/doc/content
    moose:
        root_dir: ${MOOSE_DIR}/framework/doc/content
        content:
            - js/*
            - css/*
            - contrib/**
            - media/**
Renderer:
    type: MooseDocs.base.MaterializeRenderer
Extensions:
    MooseDocs.extensions.navigation:
        name: swift
        repo: https://github.com/idaholab/swift
        menu:
            Getting Started:
                Installing Swift: installation.md
                Help Forum: https://github.com/idaholab/swift/discussions
            Documentation:
                Syntax Index: syntax/index.md
                Source Index: source/index.md
            Examples: examples.md
            Citing: citing.md
    MooseDocs.extensions.appsyntax:
        executable: ${ROOT_DIR}
        remove: !include ${MOOSE_DIR}/framework/doc/remove.yml
        includes:
            - include
